server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${SERVER_PORT:8761}/eureka/